// playground/vue3/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import HelloWorld from "./components/HelloWorld.vue";
import { serverScripts } from "./lib/gas";

const name = ref<string>("");
const message = ref<string | null>(null);

const sayHello = async (name: string) => {
  message.value = null;
  const result = await serverScripts.sayHello(name);
  message.value = result;
};
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
    <div>
      <input v-model="name" placeholder="input your name..." />
      <p v-if="message">{{ message }}</p>
      <button v-else v-on:click="() => sayHello(name)" :style="{ marginLeft: '10px'}">Say hello</button>
			</div>
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// playground/react-with-vite-plugin/src/App.tsx
import { useState } from "react";
import viteLogo from "/vite.svg";
import reactLogo from "./assets/react.svg";
import "./App.css";
import { serverScripts } from "./lib/gas";

function App() {
	const [count, setCount] = useState(0);
	const [name, setName] = useState("");
	const [message, setMessage] = useState<string | null>(null);

	const sayHello = async (name: string) => {
		setMessage(null);
		const result = await serverScripts.sayHello(name);
		setMessage(result);
	};

	return (
		<>
			<div>
				<a href="https://vite.dev" target="_blank" rel="noreferrer">
					<img src={viteLogo} className="logo" alt="Vite logo" />
				</a>
				<a href="https://react.dev" target="_blank" rel="noreferrer">
					<img src={reactLogo} className="logo react" alt="React logo" />
				</a>
			</div>
			<h1>Vite + React</h1>
			<div className="card">
				<button onClick={() => setCount((count) => count + 1)}>
					count is {count}
				</button>
				<p>
					Edit <code>src/App.tsx</code> and save to test HMR
				</p>
			</div>
			<div>
				<input value={name} placeholder="input your name..." onChange={(e) => setName(e.target.value)} />
				{message ? <p>{message}</p> : <button onClick={() => sayHello(name)} style={{ marginLeft: '10px'}}>Say hello</button>}
			</div>
			<p className="read-the-docs">
				Click on the Vite and React logos to learn more
			</p>
		</>
	);
}

export default App;
